### PR TITLE
ignore que files in music lib

### PR DESCRIPTION
**Pull request by bitkeeper**
Add a default .mpdignore to ignore *.cue files.

### CODE REVIEW

**Comment by moodeaudio** [comment]
Added corrected line manually to local repo. Will merge to Master after release.

**Comment by bitkeeper** [comment]
hmm ?? this one was never used? Maybe you intend https://github.com/moode-player/moode/pull/334 this one ?

**Comment by bitkeeper** [comment]
No need to modify mosbuild_worker.sh anylonger, because it now an option.

**Comment by moodeaudio** [comment]
Ah, got it. I'll fix.

**Pull request closed without merging**
